services:
  db:
    container_name: monorepo-scaffold-db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
      - ./init.sql://docker-entrypoint-initdb.d/init.sql
    networks:
      - db
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  db:
    driver: bridge
    name: monorepo-scaffold-db
volumes:
  db:
