packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@prisma/client': ^6.12.0
  '@turbo/gen': ^2.5.5
  '@types/node': ^20.12.7
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.0
  '@typescript-eslint/eslint-plugin': ^7.18.0
  '@typescript-eslint/parser': ^7.18.0
  '@vitest/ui': ^1.6.0
  '@t3-oss/env-core': ^0.13.8
  eslint: ^8.57.0
  eslint-config-prettier: ^9.1.0
  dotenv-cli: ^8.0.0
  hono: ^4.8.0
  next: ^15.4.1
  prettier: ^3.6.2
  prisma: ^6.12.0
  react: ^19.1.0
  react-dom: ^19.1.0
  tsup: ^8.5.0
  tsx: ^4.10.5
  turbo: ^2.5.5
  typescript: ^5.8.3
  vitest: ^1.6.0
  zod: ^3.23.6
