packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  # Core Build Tools & TypeScript
  typescript: ^5.4.5
  "@types/node": ^20.12.7
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  tsx: ^4.10.5

  # Linting & Formatting (shared across all packages)
  eslint: ^8.57.0
  prettier: ^3.2.5
  "@typescript-eslint/eslint-plugin": ^7.18.0
  "@typescript-eslint/parser": ^7.18.0
  eslint-config-prettier: ^9.1.0

  # Testing (shared across packages)
  vitest: ^1.6.0
  "@vitest/ui": ^1.6.0

  # Core Frameworks (used as peer deps and in multiple apps)
  react: ^19.1.0
  react-dom: ^19.1.0
  next: ^15.0.0
  hono: ^4.4.0

  # Commonly used utilities
  zod: ^3.23.6

  # Turborepo
  turbo: ^2.5.4
  "@turbo/gen": ^2.5.4
